name: insta_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
# ^ core
  shared_preferences: ^2.5.2
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.1
  get_it: ^8.0.2

# ^ Api
  dio: ^5.8.0
  retrofit: ^4.4.0
  json_annotation: ^4.9.0

# ^ Bloc
  flutter_bloc: ^8.1.6
# ^ Firebase
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5

# ^ ui
  cached_network_image: ^3.3.1
  google_nav_bar: ^5.0.7
  ionicons: ^0.2.2
  awesome_snackbar_content: ^0.1.5
  video_player: ^2.9.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  retrofit_generator: '>=8.0.0 <10.0.0' 
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
